# This file is Copyright (c) 2019 Florent Kermarrec <florent@enjoy-digital.fr>
# License: BSD

from math import ceil

from migen import *
from migen.genlib.cdc import MultiReg
from migen.genlib.misc import WaitTimer

# Constants/Helpers --------------------------------------------------------------------------------

lfps_clk_freq_min = 1/100e-9
lfps_clk_freq_max = 1/20e-9

class LFPSTiming:
    def __init__(self, t_typ=None, t_min=None, t_max=None):
        self.t_typ = t_typ
        self.t_min = t_min
        self.t_max = t_max
        assert t_min is not None
        assert t_max is not None
        self.range = (t_min, t_max)

class LFPS:
    def __init__(self, burst, repeat=None, cycles=None):
        self.burst  = burst
        self.repeat = repeat
        self.cycles = None

def ns_to_cycles(clk_freq, t):
    return ceil(t*clk_freq)

# LFPS Definitions ---------------------------------------------------------------------------------

# TODO: add LFPS Handshake timings

PollingLFPSBurst  = LFPSTiming(t_typ=1.0e-6,  t_min=0.6e-6, t_max=1.4e-6)
PollingLFPSRepeat = LFPSTiming(t_typ=10.0e-6, t_min=6.0e-6, t_max=14.0e-6)
PollingLFPS       = LFPS(burst=PollingLFPSBurst, repeat=PollingLFPSRepeat)

PingLFPSBurst     = LFPSTiming(t_typ=None,     t_min=40.0e-9,  t_max=200.0e-9)
PingLFPSRepeat    = LFPSTiming(t_typ=200.0e-3, t_min=160.0e-3, t_max=240.0e-3)
PingLFPS          = LFPS(burst=PingLFPSBurst, repeat=PingLFPSRepeat, cycles=2)

ResetLFPSBurst    = LFPSTiming(t_typ=100.0e-3, t_min=80.0e-3,  t_max=120.0e-3)
ResetLFPS         = LFPS(burst=ResetLFPSBurst)

U1ExitLFPSBurst   = LFPSTiming(t_typ=None, t_min=300.0e-9, t_max=900.0e-9) # FIXME: t_max=900.0e-9/2.0e-6?
U1ExitLFPS        = LFPS(burst=U1ExitLFPSBurst)

U2LFPSBurst       = LFPSTiming(t_typ=None, t_min=80.0e-3, t_max=2.0e-3)
U2LFPS            = LFPS(burst=U2LFPSBurst)

LoopbackExitLFPS  = U2LFPS

U3WakeupLFPSBurst = LFPSTiming(t_typ=None, t_min=80.0e-3, t_max=10.0e-3)
U3WakeupLFPS      = LFPS(burst=U3WakeupLFPSBurst)

# LFPS Checker -------------------------------------------------------------------------------------

class LFPSChecker(Module):
    def __init__(self, sys_clk_freq):
        self.idle    = Signal() # i
        self.polling = Signal() # o

        # # #

        # Idle Resynchronization -------------------------------------------------------------------
        idle          = Signal()
        self.specials += MultiReg(self.idle, idle)

        # Polling LFPS Detection -------------------------------------------------------------------
        burst_cycles  = ns_to_cycles(sys_clk_freq, PollingLFPS.burst.t_typ)
        repeat_cycles = ns_to_cycles(sys_clk_freq, PollingLFPS.repeat.t_typ)
        self.count = count = Signal(max=max(burst_cycles, repeat_cycles))
        self.found = found = Signal()

        self.submodules.fsm = fsm = FSM(reset_state="TBURST")
        fsm.act("TBURST",
            If(count == 0,
                If(idle == 0,
                    NextValue(count, burst_cycles - 1),
                ).Else(
                    NextValue(count, repeat_cycles - 2*burst_cycles - 1),
                    NextState("TREPEAT")
                )
            ).Else(
                NextValue(count, count - 1)
            ),
            If(found & (idle == 0),
                self.polling.eq(1),
                NextValue(found, 0)
            ),
        )
        fsm.act("TREPEAT",
            NextValue(count, count - 1),
            If((count == 0) | (idle == 0),
                NextValue(found, (count == 0)),
                NextValue(count, burst_cycles - 1),
                NextState("TBURST")
            )
        )

# LFPS Generator -----------------------------------------------------------------------------------

class LFPSBurstGenerator(Module):
    """LFPS Burst Generator

    Generate a LFPS Burst of configurable length on the TX lanes. The LFPS clock is generated by
    sending a alternating ones/zeroes data pattern on the parallel interface of the transceiver.
    """
    def __init__(self, sys_clk_freq, lfps_clk_freq):
        # Control
        self.start  = Signal()   # i
        self.done   = Signal()   # o
        self.length = Signal(32) # i

        # Transceiver
        self.tx_idle    = Signal(reset=1) # o
        self.tx_pattern = Signal(20)      # o

        # # #

        # Assertions -------------------------------------------------------------------------------
        # The LFPS Burst has a minimum and maximum allowed period.
        assert lfps_clk_freq >= lfps_clk_freq_min
        assert lfps_clk_freq <= lfps_clk_freq_max

        # LFPS Burst Clock generation --------------------------------------------------------------
        clk = Signal()
        clk_timer = WaitTimer(ceil(sys_clk_freq/(2*lfps_clk_freq)) - 1)
        clk_timer = ResetInserter()(clk_timer)
        self.submodules += clk_timer
        self.comb += clk_timer.wait.eq(~clk_timer.done)
        self.sync += If(clk_timer.done, clk.eq(~clk))

        # LFPS Burst generation --------------------------------------------------------------------
        count = Signal.like(self.length)
        self.submodules.fsm = fsm = FSM(reset_state="IDLE")
        fsm.act("IDLE",
            self.done.eq(1),
            clk_timer.reset.eq(1),
            NextValue(count, self.length),
            If(self.start,
                NextState("BURST")
            )
        )
        fsm.act("BURST",
            self.tx_idle.eq(0),
            self.tx_pattern.eq(Replicate(clk, 20)),
            NextValue(count, count - 1),
            If(count == 0,
                NextState("IDLE")
            )
        )

# LFPS Generator -----------------------------------------------------------------------------------

class LFPSGenerator(Module):
    """LFPS Generator

    Generate LFPS signals on the TX lanes from simple user controls (User just have to sets LFPS
    control signal to 1 to generate a specific LFPS, this module will handle LFPS clock genration,
    LFPS Burst length and repeat).
    """
    def __init__(self, sys_clk_freq, lfps_clk_freq):
        # Control
        self.polling = Signal()      # i

        # Transceiver
        self.tx_idle    = Signal()   # o
        self.tx_pattern = Signal(20) # o

        # # #

        # Burst Generator ------------------------------------------------------------------------
        burst_generator = LFPSBurstGenerator(sys_clk_freq=sys_clk_freq, lfps_clk_freq=lfps_clk_freq)
        self.submodules += burst_generator

        # Burst Generation -------------------------------------------------------------------------
        burst_repeat_count = Signal(32)
        self.submodules.fsm = fsm = FSM(reset_state="IDLE")
        fsm.act("IDLE",
            self.tx_idle.eq(0),
            If(self.polling,
                self.tx_idle.eq(1),
                NextValue(burst_generator.start, 1),
                NextValue(burst_generator.length, int(sys_clk_freq*PollingLFPSBurst.t_typ)),
                NextValue(burst_repeat_count,     int(sys_clk_freq*PollingLFPSRepeat.t_typ)),
                NextState("RUN")
            )
        )
        fsm.act("RUN",
            NextValue(burst_generator.start, 0),
            self.tx_idle.eq(burst_generator.tx_idle),
            self.tx_pattern.eq(burst_generator.tx_pattern),
            NextValue(burst_repeat_count, burst_repeat_count - 1),
            If(burst_repeat_count == 0,
                NextState("IDLE")
            ),
        )

# LFPS Unit ----------------------------------------------------------------------------------------

class LFPSUnit(Module):
    def __init__(self, sys_clk_freq, serdes):
        self.rx_polling = Signal() # o
        self.tx_polling = Signal() # i

        # # #

        # LFPS Checker -----------------------------------------------------------------------------
        checker = LFPSChecker(sys_clk_freq=sys_clk_freq)
        self.submodules += checker
        self.comb += checker.idle.eq(serdes.rx_idle)
        self.comb += self.rx_polling.eq(checker.polling)

        # LFPS Generator ---------------------------------------------------------------------------
        generator = LFPSGenerator(sys_clk_freq=sys_clk_freq, lfps_clk_freq=25e6)
        self.submodules += generator
        self.comb += [
            If(self.tx_polling,
                generator.polling.eq(1),
                serdes.tx_idle.eq(generator.tx_idle),
                serdes.tx_pattern.eq(generator.tx_pattern)
            ).Else(
                 serdes.tx_idle.eq(0)
            )
        ]
